version: '3'
services:
  db:
    image: postgres
    volumes:
      - /database:/data/db
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: pguser
        POSTGRES_PASSWORD: pguser
        POSTGRES_DB: pgdb
