version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/opt/app
    links:
      - postgres
    environment:
      - NODE_ENV=dev
    working_dir: /opt/app
    command: yarn start

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    ports:
      - 5432:5432
    volumes:
      - /database:/var/lib/postgresql/data


